name: Build Pull Request

on:
  workflow_call:
    inputs:
      java-version:
        description: Version of the JDK to use to run the Gradle command.
        required: false
        default: '17'
        type: string
      distribution:
        description: Distribution of the JDK to use to run the Gradle command.
        required: false
        default: 'temurin'
        type: string
    secrets:
      DEVELOCITY_ACCESS_KEY:
        required: false

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ inputs.java-version }}
        uses: spring-io/spring-gradle-build-action@v2
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
      - name: Build with Gradle
        run: ./gradlew clean build --continue
