name: Deploy Docs

on:
  workflow_call:
    inputs:
      should-deploy-docs:
        description: Whether docs should be deployed.
        required: true
        type: string
    outputs:
      docs-deployed:
        description: Whether docs were actually deployed.
        value: ${{ jobs.deploy-docs.outputs.docs-deployed }}
    secrets:
      GRADLE_ENTERPRISE_CACHE_USER:
        required: false
      GRADLE_ENTERPRISE_CACHE_PASSWORD:
        required: false
      GRADLE_ENTERPRISE_SECRET_ACCESS_KEY:
        required: false
      DOCS_USERNAME:
        required: false
      DOCS_SSH_KEY:
        required: false
      DOCS_HOST:
        required: false

env:
  GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USER }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
  DOCS_USERNAME: ${{ secrets.DOCS_USERNAME }}
  DOCS_SSH_KEY: ${{ secrets.DOCS_SSH_KEY }}
  DOCS_HOST: ${{ secrets.DOCS_HOST }}

jobs:
  deploy-docs:
    name: Deploy Docs
    if: ${{ inputs.should-deploy-docs == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      docs-deployed: ${{ steps.docs-deployed.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: spring-io/spring-gradle-build-action@v2
      - name: Deploy Docs
        run: ./gradlew deployDocs -PdeployDocsSshKey="$DOCS_SSH_KEY" -PdeployDocsSshUsername="$DOCS_USERNAME" -PdeployDocsHost="$DOCS_HOST" --stacktrace
      - id: docs-deployed
        name: Docs Deployed
        run: echo "result=true" >> $GITHUB_OUTPUT
